WITH AVG_SCORE AS(
    SELECT i.REST_ID, ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
    FROM REST_INFO i
    JOIN REST_REVIEW r
        ON i.REST_ID = r.REST_ID
    WHERE i.ADDRESS LIKE '서울%'
    GROUP BY i.REST_ID
)

SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, a.SCORE
FROM REST_INFO i
JOIN AVG_SCORE a
    ON i.REST_ID = a.REST_ID
ORDER BY a.SCORE DESC, i.FAVORITES DESC;